### ISSUE TITLE
Installing Script Error

### ISSUE THREAD

**Issue by pbl4845** [pkeroulas/st2110-toolkit#2]
Hi Patrick,

May i get some guidande from your side?

I'm trying to install the 2110 toolkit using your install script as described in the README.md, but i'm getting the following error.
-bash: syntax error near unexpected token `newline'

I compiled FFmpeg 5.0 yesterday, just in case has something to do. Should i delete it and start fresh new?

Thanks!

**Comment by pbl4845** [comment]
i only modified st2110.conf with the  following changes in order to use the proper eht ports:

MGMT_IFACE=em1

MEDIA_IFACE_0=enp66s0f1
MEDIA_IFACE_1=enp66s0f0
MEDIA_IFACE=$MEDIA_IFACE_0

PTP_IFACE_0=enp66s0f1 # ptp4l
PTP_IFACE_1=enp66s0f0 # phc2sys

**Comment by pkeroulas** [comment]
I rarely install from scratch and you might encounter some errors depending you distribution.

**Comment by pbl4845** [comment]
Thing is I tried also renaming ffmpeg to old, getting same results. So it
must be something else.

I’m on Centos7

**Comment by pkeroulas** [comment]
I don't have install issue on Centos 8, can you `git pull`?
And please, can you give me the exact command that actual fails and the output before the error message.

**Comment by boyexpert** [comment]
Hi,
I'm trying to run install.sh , it get result below
can you show me what happen?

+ case "$1" in
+ echo 'Usage: ./install.sh <common|ptp|transcoder|capture|ebulist|nmos>'
Usage: ./install.sh <common|ptp|transcoder|capture|ebulist|nmos>
+ set +x

**Comment by pkeroulas** [comment]
> 

@boyexpert this is because you need to add a parameter corresponding to your use case.
I'll make the message more explicit.

**Comment by pkeroulas** [comment]
https://github.com/pkeroulas/st2110-toolkit#install

**Comment by boyexpert** [comment]
@pkeroulas thanks for your support!
i tend to install transcoder section (for ffmpeg extention) on Ubuntu 20.04
before using, how to check all the installment done?

**Comment by pkeroulas** [comment]
Usually, when the install process breaks, `ffmpeg` compile fails too. Try to execute ffmep with no option and you should see the following compile options: `  configuration: --prefix=/usr/local --extra-cflags=-I/usr/local/include --extra-ldflags=-L/usr/local/lib --bindir=/usr/local/bin --extra-libs=-ldl --enable-version3 --enable-gpl --enable-nonfree --enable-postproc --enable-avresample --enable-libx264 --enable-libfdk-aac --enable-libmp3lame --disable-ffplay --disable-ffprobe --enable-small --disable-stripping --disable-debug`
