### ISSUE TITLE
"urllib2.urlerror urlopen error errno 111 connection refused" when running get_sdp.py 

### ISSUE THREAD

**Issue by boyexpert** [pkeroulas/st2110-toolkit#3]
i don't understand above error when try to get sdp file by running get_sdp.py 
pls help me asap!!

**Comment by pkeroulas** [comment]
Do you have a response for this command?
`curl http://[your Embrionix IP here]/emsfp/node/v1/sdp/`

**Comment by boyexpert** [comment]
I'm running to connect to NIC port on my own PC

**Comment by pkeroulas** [comment]
From the script description: `get_sdp.py - helper script to fetch SDP file from Embrionix sender` so it uses Embrionix (now Riedel) API. If your PC is serving an NMOS node, please see `./nmos/get_sdp.sh`.

**Comment by boyexpert** [comment]
Embrionix (now Riedel) API may not be installed on my PC
can u help me install it ? (by a link)

**Comment by pkeroulas** [comment]
It's going to be hard: https://www.riedel.net/index.php?id=629
What are you trying to achieve?
Do you have any ST 2110 source?

**Comment by boyexpert** [comment]
i'm trying to use transcoder to convert st2110 source to output (h264) and monitor it on screen
it'll work like gstreamer tool

**Comment by boyexpert** [comment]
By the way, when i run /nmos/get_sdp.py, i got some response
![Uploading F672A676-046A-4990-BFAD-B04DD7807DC6.jpeg…]()

**Comment by boyexpert** [comment]
By the way, i got some responses when running /nmos/get_sdp.py
![ADEE0FAF-4FA1-434D-A4A3-C67428DB9388](https://user-images.githubusercontent.com/62916959/162338863-4f34f88c-e1e6-4b93-ad19-af4c882ecc44.jpeg)

**Comment by pkeroulas** [comment]
ffmpeg takes an SDP as input, right. But you won't get any SDP from your PC.
Take that [sample](https://github.com/pkeroulas/st2110-toolkit/blob/master/doc/sdp.sample), strip the audio (225.0.1.16) and the ancillary (225.17.0.16), and modify the video (225.164.5.190) with the network and video format corresponding to the output of your gstreamer process.

**Comment by boyexpert** [comment]
i have to generate a sdp file from my st2110 source by running get_sdp.py or another  to input a new file by coding
somewhen i can't edit file manually

**Comment by pkeroulas** [comment]
Hi, if your source is a software running on a regular PC, you won't magically get a SDP from there.
You'd rather have to craft the SDP from the example above or [here](https://www.embrionix.com/storage/app/media/white-papers/SDP%20Whitepaper%20ST2110.pdf)

**Comment by boyexpert** [comment]
so, i'll try it.
thank for your support!
